name: Test Driver

on:
  push:
    branches: [n_api, master]
  pull_request:
    branches: [n_api, master]
  workflow_dispatch:

jobs:
  test-linux:
    name: Test Linux - Node ${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
    runs-on: ubuntu-20.04
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourStrong!Passw0rd
          MSSQL_PID: Developer
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    
    - name: Install Linux dependencies
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
        curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 unixodbc-dev gcc-10 g++-10
        echo "CC=gcc-10" >> $GITHUB_ENV
        echo "CXX=g++-10" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: npm install
    
    - name: Build TypeScript
      run: npm run build
    
    - name: Build test TypeScript
      run: npm run build:test
    
    - name: Setup test configuration
      run: |
        mkdir -p test
        cat > test/test-config.json << EOF
        {
          "server": "localhost",
          "user": "sa",
          "password": "YourStrong!Passw0rd",
          "database": "master",
          "driver": "ODBC Driver 18 for SQL Server",
          "options": {
            "encrypt": false,
            "trustServerCertificate": true
          }
        }
        EOF
    
    - name: Run tests
      run: npm test
      timeout-minutes: 30
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-linux-node${{ matrix.node }}
        path: |
          test-results/
          mochawesome-report/

  test-windows:
    name: Test Windows - Node ${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    
    - name: Install SQL Server LocalDB
      shell: powershell
      run: |
        Write-Host "Installing SQL Server 2022 LocalDB..."
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri https://download.microsoft.com/download/3/8/d/38de7036-2433-4207-8eae-06e247e17b25/SqlLocalDB.msi -OutFile SqlLocalDB.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i SqlLocalDB.msi /quiet /qn IACCEPTSQLLOCALDBLICENSETERMS=YES'
        
        # Create and start LocalDB instance
        & "C:\Program Files\Microsoft SQL Server\160\Tools\Binn\SqlLocalDB.exe" create "testinstance" -s
        & "C:\Program Files\Microsoft SQL Server\160\Tools\Binn\SqlLocalDB.exe" info "testinstance"
    
    - name: Install dependencies
      run: npm install
    
    - name: Build TypeScript
      run: npm run build
    
    - name: Build test TypeScript
      run: npm run build:test
    
    - name: Setup test configuration
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path test
        @'
        {
          "server": "(localdb)\\testinstance",
          "database": "master",
          "options": {
            "trustedConnection": true
          }
        }
        '@ | Out-File -FilePath test\test-config.json -Encoding UTF8
    
    - name: Run tests
      run: npm test
      timeout-minutes: 30
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-windows-node${{ matrix.node }}
        path: |
          test-results/
          mochawesome-report/